### ISSUE TITLE
[Java] Fix failed test

### ISSUE THREAD

**Issue by dkurt** [openvinotoolkit/openvino_contrib#132]
```
InferRequestTests > testGetPerformanceCounts FAILED
    java.lang.AssertionError: Map size expected:<10> but was:<22>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at InferRequestTests.testGetPerformanceCounts(InferRequestTests.java:57)
```
source: https://dev.azure.com/openvinoci/dldt/_build/results?buildId=87114&view=logs&j=0609cd82-f9f7-5e70-371c-89fca78031ab&t=0971f6e8-539b-5170-a800-5a6fa6f3c74b

**Comment by likholat** [comment]
Layers were changed:
| Name before  | Name now |
| ------------- | ------------- |
| 19/Fused_Add_  | Content Cell  |
| 21  | Content Cell  |
| 21  | Content Cell  |
| 21  | Content Cell  |
| 21  | Content Cell  |
| 21  | Content Cell  |

("19/Fused_Add_");
        layer_name.add("21");
        layer_name.add("22");
        layer_name.add("23");
        layer_name.add("24/Fused_Add_");
        layer_name.add("26");
        layer_name.add("27");
        layer_name.add("29");
        layer_name.add("fc_out");
        layer_name.add("out_fc_out");

**Comment by alvoron** [comment]
@dkurt  @likholat are we going to align the test with the modified network? Or other actions are required here?

**Comment by dkurt** [comment]
For now test is disabled. Well, it's better to check only API but relax the requirements to pass the test.

**Comment by alvoron** [comment]
@dkurt is it supposed that @likholat will change the test? Or somebody else needs to update it?

**Comment by dkurt** [comment]
@likholat, please enable the test with the relaxed check
