### ISSUE TITLE
[ ERROR ] std::bad_cast in benchmark_app sample with arm plugin in 2021.4

### ISSUE THREAD

**Issue by okih** [openvinotoolkit/openvino_contrib#175]
It seems "std::bad_cast" occurs when calling ie.GetConfig(ds.first, key).as<std::string>() for key value "CPU_THROUGHPUT_STREAMS".

platform: Raspberry Pi 4, utuntu 18.04 64bit
version: openvino 2021.4

P.S
ie.GetConfig(device, configKey) in hello_query_deive sample works without error in 2021.4.  
It aborts in 2021.3.

<< 2021.4 >>
Available devices:
CPU
        SUPPORTED_METRICS:
                AVAILABLE_DEVICES : [ NEON ]
                FULL_DEVICE_NAME : arm_compute::NEON
                OPTIMIZATION_CAPABILITIES : [ FP32 FP16 ]
        SUPPORTED_CONFIG_KEYS (default values):
                PERF_COUNT : YES
                CPU_THROUGHPUT_STREAMS : 1
                CPU_BIND_THREAD : NO
                CPU_THREADS_NUM : 0
                CPU_THREADS_PER_STREAM : 4

<< 2021.3 >>
Available devices:
        Device: ARM
        Metrics:
                SUPPORTED_METRICS : [ AVAILABLE_DEVICES SUPPORTED_METRICS SUPPORTED_CONFIG_KEYS FULL_DEVICE_NAME OPTIMIZATION_CAPABILITIES ]
                SUPPORTED_CONFIG_KEYS : [ PERF_COUNT CPU_THROUGHPUT_STREAMS CPU_BIND_THREAD CPU_THREADS_NUM CPU_THREADS_PER_STREAM ]
                FULL_DEVICE_NAME : arm_compute::NEON
                OPTIMIZATION_CAPABILITIES : [ FP32 FP16 ]
        Default values for device configuration keys:
                PERF_COUNT : YES
                CPU_THROUGHPUT_STREAMS : [NOT_FOUND] : CPU_THROUGHPUT_STREAMS

Beat Regards,

**Comment by alvoron** [comment]
@okih thank you for raising the issue.
I reproduced it, indeed, bad_cast occurs on `ie.GetConfig` operation. To workaround the issue you can change the cast, the following one works to me: `std::to_string(ie.GetConfig(ds.first, key).as<int>())`
I'll contact IE sample authors to decide how to fix it accurately.
Please let me know whether provided workaround works to you or not.

**Comment by okih** [comment]
Thank you for reply,
I confirmed changing the cast fixed the issue with armPlugin.  Obviously it causes bad_cast with MKLDNNPlugin  - CPU plugin on x86_64 platform.
I suppose there would be some incompatibility of KEY type declaration between armPlugin and the x86_64 CPU plugin. I hope I can use them in a same manner.
Best Regards,

**Comment by alvoron** [comment]
The following changes will solve cast issue:
https://github.com/openvinotoolkit/openvino_contrib/pull/181
https://github.com/openvinotoolkit/openvino/pull/6830

**Comment by alvoron** [comment]
@okih both PRs are merged to master, the issue should be resolved.
Please reopen the issue if it is still reproducible.
