### ISSUE TITLE
FPS on the raspberry pi 4

### ISSUE THREAD

**Issue by zhaoxuejun1234** [openvinotoolkit/openvino_contrib#203]
I finished the build process for Ubuntu 18.04 and proceeded a object detection inference. The average inference latency is 328ms. But the average inference latency on a intel 2.6G Hz CPU is around 20ms. Is this normal? What can I do to improve it?

**Comment by alvoron** [comment]
@zhaoxuejun1234 thank you for testing the plugin!
what network do you use? can you share your demo sample?

**Comment by zhaoxuejun1234** [comment]
> @zhaoxuejun1234 thank you for testing the plugin!
> what network do you use? can you share your demo sample?

I used an object detection model named nanodet,which can be found on https://github.com/RangiLyu/nanodet. I just added codes for getting the inference time. The demo could be modified and shared if you are interested.

**Comment by alvoron** [comment]
@zhaoxuejun1234 if you don't mind could you please share exact your sample so we would be able to compare results?
