### ISSUE TITLE
OV Java API 2.0

### ISSUE THREAD

**Issue by dkurt** [openvinotoolkit/openvino_contrib#220]
Create bindings for new API: https://github.com/openvinotoolkit/openvino/blob/master/inference-engine/src/inference_engine/include/openvino/runtime/

**Comment by allnes** [comment]
Hi, I have a question.
When could we expect the release of OpenVINO 2.0 Java API?
Thank you!

**Comment by dkurt** [comment]
Hi! Sorry for delayed response. We have not prioritized it yet. Am I right that with 2.0 API release, old API will be also available? So Java API won't break in next release.

**Comment by allnes** [comment]
> Hi! Sorry for delayed response. We have not prioritized it yet. Am I right that with 2.0 API release, old API will be also available? So Java API won't break in next release.

Yes, it's right, but I know that old api will become as deprecated api. If this case don't affect Java API thaе the issue can to be closed.

**Comment by dkurt** [comment]
Anyway we need to align Java API with a mew API. @likholat, lat me assign this issue to you.
