### ISSUE TITLE
'OpenVINOTensor' object has no attribute 'is_floating_point'

### ISSUE THREAD

**Issue by tersekmatija** [openvinotoolkit/openvino_contrib#249]
Hey,
I am getting this error:
```
Exception: Exception occurred during running replacer "REPLACEMENT_ID (<class 'mo_extensions.load.pytorch.loader.PyTorchLoader'>)": 'OpenVINOTensor' object has no attribute 'is_floating_point'
```
when trying to run the following code:
```
import torchvision.models as models
import torch

# Create model
model = models.detection.mask_rcnn.maskrcnn_resnet50_fpn(pretrained=True,box_detections_per_img=25, rpn_post_nms_top_n_test=200)
model.eval()
print(model(torch.rand([1, 3, 800, 800])))

# Convert to OpenVINO IR
import mo_pytorch
mo_pytorch.convert(model, input_shape=[1, 3, 800, 800], model_name='maskrcnn_resnet50_fpn')
```

I am using the latest 2021.4.2 LTS version of OpenVINO and I've added the mo_pytorch model to the PYTHONPATH.

**Comment by dkurt** [comment]
Hi! Can you please specify which versions of PyTorch and Torchvision are used? We tested woth torch==1.7.0 and torchvision==0.8.1

**Comment by tersekmatija** [comment]
Hey, I tried with torch==1.8.2 and torchvision==0.9.2. I downgraded the versions now and it worked, thanks!
Seems that with higher versions the export is not supported.

**Comment by dkurt** [comment]
@tersekmatija, thanks for the details, I will open a pull request with a fix and let you know.

**Comment by dkurt** [comment]
Fix is here: https://github.com/openvinotoolkit/openvino_contrib/pull/217
