### ISSUE TITLE
Failed Windows build

### ISSUE THREAD

**Issue by dkurt** [openvinotoolkit/openvino_contrib#269]
Failed "Install dependencies" step. Example: https://dev.azure.com/openvinoci/dldt/_build/results?buildId=234614&view=logs&j=4c86bc1b-1091-5192-4404-c74dfaad23e7&t=d216f1e9-c2b5-54b5-eceb-b0e7ea6b3dcc
```
Access is denied.
Expand-Archive : The path 'ninja-win.zip' either does not exist or is not a valid file system path.
At line:1 char:1
+ Expand-Archive -Force ninja-win.zip
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (ninja-win.zip:String) [Expand-Archive], InvalidOperationException
    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive
```

/cc @azhogov

**Comment by azhogov** [comment]
Fixed: https://github.com/openvinotoolkit/openvino_contrib/commit/e17b8e1f91b44f189a0f721ba3c88b45aa22c041

**Comment by dkurt** [comment]
@azhogov, thanks!
