### ISSUE TITLE
[ARM Plugin] Native Compile - Apple M1 Compile Error...

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_contrib#27]
I believe we cannot use gcc '-march=armv7-a' in Apple arm compiler? I assume apple gcc (arm64) is not supported? 

`[ 59%] Built target armPlugin_cpplint
Scanning dependencies of target cpplint_all
[ 59%] Built target cpplint_all
Scanning dependencies of target arm_compute_static_libs
[ 60%] Build Arm Compute Library
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `arm_compute' is up to date.
scons: `support' is up to date.
scons: building associated VariantDir targets: /Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/utils
scons: `utils' is up to date.
scons: `include/half' is up to date.
scons: `include/stb' is up to date.
scons: `include/libnpy' is up to date.
scons: `include/linux' is up to date.
scons: `include/CL' is up to date.
create_version_file(["/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/arm_compute_version.embed"], [])
g++ -o /Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/AccessWindowAutoPadding.o -c -Wall -DARCH_ARM -Wextra -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -std=gnu++11 -Woverloaded-virtual -Wformat-security -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-overlength-strings -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -Wno-ignored-attributes -DENABLE_FP16_KERNELS -DENABLE_FP32_KERNELS -DENABLE_QASYMM8_KERNELS -DENABLE_QASYMM8_SIGNED_KERNELS -DENABLE_QSYMM16_KERNELS -Werror -Wno-psabi -O3 -fPIC -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_VERSION_MAJOR=21 -DARM_COMPUTE_VERSION_MINOR=0 -DARM_COMPUTE_VERSION_PATCH=0 -Iinclude -I. -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core -Isrc/core -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/common -Isrc/core/NEON/kernels/convolution/common -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/winograd -Isrc/core/NEON/kernels/convolution/winograd -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/depthwise -Isrc/core/NEON/kernels/convolution/depthwise -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/assembly -Isrc/core/NEON/kernels/assembly -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/arm_compute/core/NEON/kernels/assembly -Iarm_compute/core/NEON/kernels/assembly src/core/AccessWindowAutoPadding.cpp
g++ -o /Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/AccessWindowStatic.o -c -Wall -DARCH_ARM -Wextra -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -std=gnu++11 -Woverloaded-virtual -Wformat-security -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-overlength-strings -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -Wno-ignored-attributes -DENABLE_FP16_KERNELS -DENABLE_FP32_KERNELS -DENABLE_QASYMM8_KERNELS -DENABLE_QASYMM8_SIGNED_KERNELS -DENABLE_QSYMM16_KERNELS -Werror -Wno-psabi -O3 -fPIC -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_VERSION_MAJOR=21 -DARM_COMPUTE_VERSION_MINOR=0 -DARM_COMPUTE_VERSION_PATCH=0 -Iinclude -I. -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core -Isrc/core -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/common -Isrc/core/NEON/kernels/convolution/common -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/winograd -Isrc/core/NEON/kernels/convolution/winograd -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/depthwise -Isrc/core/NEON/kernels/convolution/depthwise -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/assembly -Isrc/core/NEON/kernels/assembly -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/arm_compute/core/NEON/kernels/assembly -Iarm_compute/core/NEON/kernels/assembly src/core/AccessWindowStatic.cpp
clang: error: the clang compiler does not support '-march=armv7-a'
g++ -o /Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/AccessWindowTranspose.o -c -Wall -DARCH_ARM -Wextra -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -std=gnu++11 -Woverloaded-virtual -Wformat-security -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-overlength-strings -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -Wno-ignored-attributes -DENABLE_FP16_KERNELS -DENABLE_FP32_KERNELS -DENABLE_QASYMM8_KERNELS -DENABLE_QASYMM8_SIGNED_KERNELS -DENABLE_QSYMM16_KERNELS -Werror -Wno-psabi -O3 -fPIC -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_VERSION_MAJOR=21 -DARM_COMPUTE_VERSION_MINOR=0 -DARM_COMPUTE_VERSION_PATCH=0 -Iinclude -I. -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core -Isrc/core -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/common -Isrc/core/NEON/kernels/convolution/common -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/winograd -Isrc/core/NEON/kernels/convolution/winograd -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/depthwise -Isrc/core/NEON/kernels/convolution/depthwise -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/assembly -Isrc/core/NEON/kernels/assembly -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/arm_compute/core/NEON/kernels/assembly -Iarm_compute/core/NEON/kernels/assembly src/core/AccessWindowTranspose.cpp
g++ -o /Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/Error.o -c -Wall -DARCH_ARM -Wextra -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -std=gnu++11 -Woverloaded-virtual -Wformat-security -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-overlength-strings -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -Wno-ignored-attributes -DENABLE_FP16_KERNELS -DENABLE_FP32_KERNELS -DENABLE_QASYMM8_KERNELS -DENABLE_QASYMM8_SIGNED_KERNELS -DENABLE_QSYMM16_KERNELS -Werror -Wno-psabi -O3 -fPIC -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_VERSION_MAJOR=21 -DARM_COMPUTE_VERSION_MINOR=0 -DARM_COMPUTE_VERSION_PATCH=0 -Iinclude -I. -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core -Isrc/core -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/common -Isrc/core/NEON/kernels/convolution/common -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/winograd -Isrc/core/NEON/kernels/convolution/winograd -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/depthwise -Isrc/core/NEON/kernels/convolution/depthwise -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/assembly -Isrc/core/NEON/kernels/assembly -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/arm_compute/core/NEON/kernels/assembly -Iarm_compute/core/NEON/kernels/assembly src/core/Error.cpp
g++ -o /Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/GPUTarget.o -c -Wall -DARCH_ARM -Wextra -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -std=gnu++11 -Woverloaded-virtual -Wformat-security -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-overlength-strings -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -Wno-ignored-attributes -DENABLE_FP16_KERNELS -DENABLE_FP32_KERNELS -DENABLE_QASYMM8_KERNELS -DENABLE_QASYMM8_SIGNED_KERNELS -DENABLE_QSYMM16_KERNELS -Werror -Wno-psabi -O3 -fPIC -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_VERSION_MAJOR=21 -DARM_COMPUTE_VERSION_MINOR=0 -DARM_COMPUTE_VERSION_PATCH=0 -Iinclude -I. -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core -Isrc/core -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/common -Isrc/core/NEON/kernels/convolution/common -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/winograd -Isrc/core/NEON/kernels/convolution/winograd -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/depthwise -Isrc/core/NEON/kernels/convolution/depthwise -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/assembly -Isrc/core/NEON/kernels/assembly -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/arm_compute/core/NEON/kernels/assembly -Iarm_compute/core/NEON/kernels/assembly src/core/GPUTarget.cpp
clang: error: the clang compiler does not support '-march=armv7-a'
clang: error: the clang compiler does not support '-march=armv7-a'
g++ -o /Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/HOGInfo.o -c -Wall -DARCH_ARM -Wextra -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -std=gnu++11 -Woverloaded-virtual -Wformat-security -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-overlength-strings -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -Wno-ignored-attributes -DENABLE_FP16_KERNELS -DENABLE_FP32_KERNELS -DENABLE_QASYMM8_KERNELS -DENABLE_QASYMM8_SIGNED_KERNELS -DENABLE_QSYMM16_KERNELS -Werror -Wno-psabi -O3 -fPIC -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_VERSION_MAJOR=21 -DARM_COMPUTE_VERSION_MINOR=0 -DARM_COMPUTE_VERSION_PATCH=0 -Iinclude -I. -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core -Isrc/core -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/common -Isrc/core/NEON/kernels/convolution/common -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/winograd -Isrc/core/NEON/kernels/convolution/winograd -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/depthwise -Isrc/core/NEON/kernels/convolution/depthwise -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/assembly -Isrc/core/NEON/kernels/assembly -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/arm_compute/core/NEON/kernels/assembly -Iarm_compute/core/NEON/kernels/assembly src/core/HOGInfo.cpp
clang: error: the clang compiler does not support '-march=armv7-a'
g++ -o /Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/Helpers.o -c -Wall -DARCH_ARM -Wextra -pedantic -Wdisabled-optimization -Wformat=2 -Winit-self -Wstrict-overflow=2 -Wswitch-default -std=gnu++11 -Woverloaded-virtual -Wformat-security -Wctor-dtor-privacy -Wsign-promo -Weffc++ -Wno-overlength-strings -Wlogical-op -Wnoexcept -Wstrict-null-sentinel -march=armv7-a -mthumb -mfpu=neon -mfloat-abi=hard -Wno-ignored-attributes -DENABLE_FP16_KERNELS -DENABLE_FP32_KERNELS -DENABLE_QASYMM8_KERNELS -DENABLE_QASYMM8_SIGNED_KERNELS -DENABLE_QSYMM16_KERNELS -Werror -Wno-psabi -O3 -fPIC -D_GLIBCXX_USE_NANOSLEEP -DARM_COMPUTE_CPP_SCHEDULER=1 -DARM_COMPUTE_VERSION_MAJOR=21 -DARM_COMPUTE_VERSION_MINOR=0 -DARM_COMPUTE_VERSION_PATCH=0 -Iinclude -I. -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core -Isrc/core -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/common -Isrc/core/NEON/kernels/convolution/common -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/winograd -Isrc/core/NEON/kernels/convolution/winograd -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/convolution/depthwise -Isrc/core/NEON/kernels/convolution/depthwise -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/NEON/kernels/assembly -Isrc/core/NEON/kernels/assembly -I/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/arm_compute/core/NEON/kernels/assembly -Iarm_compute/core/NEON/kernels/assembly src/core/Helpers.cpp
scons: *** [/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/AccessWindowAutoPadding.o] Error 1
scons: *** [/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/AccessWindowTranspose.o] Error 1
scons: *** [/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/AccessWindowStatic.o] Error 1
scons: *** [/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/Error.o] Error 1
clang: error: the clang compiler does not support '-march=armv7-a'
scons: *** [/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/GPUTarget.o] Error 1
clang: error: the clang compiler does not support '-march=armv7-a'
scons: *** [/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/HOGInfo.o] Error 1
clang: error: the clang compiler does not support '-march=armv7-a'
scons: *** [/Users/raymondlo/Documents/openvino_contrib/modules/arm_plugin/build/thirdparty/src/core/Helpers.o] Error 1
scons: building terminated because of errors.
make[2]: *** [thirdparty/libarm_compute-static.a] Error 2
make[1]: *** [thirdparty/CMakeFiles/arm_compute_static_libs.dir/all] Error 2
make: *** [all] Error 2`

**Comment by ilya-lavrenov** [comment]
Hi @raymondlo84 

The failures is in ARM compute build. Could you please try to open `modules/arm_plugin/thirdparty/ComputeLibrary/SConstruct` and fix the line 

```
if 'v7a' in env['arch']:
    env.Append(CXXFLAGS = ['-march=armv7-a', '-mthumb', '-mfpu=neon'])
```
Not to pass `-march=armv7-a` option (and maybe others as well) and check whether it helps?
