### ISSUE TITLE
Converting Mask-RCNN model trained on custom dataset to FP16 format gives error during inference

### ISSUE THREAD

**Issue by jsiebert** [openvinotoolkit/openvino_contrib#274]
Hey there,

I tried to convert the model mentioned in #271 to FP16 format and run inference with that. Converting the model to FP16 seems to work but unfortunately the Inference Engine returns an error when it tries to load the model:
```(shell)
RuntimeError: Check 'element::Type::merge(element_type, element_type, node->get_input_element_type(i))' failed at core/src/op/util/elementwise_args.cpp:22:
While validating node 'v1::Multiply Multiply_1288 (StridedSlice_562[0]:f16{1000,4}, Mul_565/mul[0]:f32{1,4}) -> ()' with friendly_name 'Multiply_1288':
Argument element types are inconsistent.
```
There are numerous warnings when exporting the model to FP16 format, especially one which is related to the operation **Mul_565** which is also mentioned in the error message of the Inference Engine:
```(shell)
[ WARNING ]  Changing Const node 'Mul_565/mul' data type from int64 to <class 'numpy.float32'> for Elementwise operation
```
I have applied all workarounds and fixes mentioned in #271.
For reference, I attach the full logs of the command line output from exporting the model and from running inference:

Export log: [log_export.txt](https://github.com/openvinotoolkit/openvino_contrib/files/7762071/log_export.txt)
Inference log: [log_inference.txt](https://github.com/openvinotoolkit/openvino_contrib/files/7762072/log_inference.txt)

Thanks and best regards,

Jens

**Comment by dkurt** [comment]
Hi! It's known issue that mo_pytorch converter works badly with `--data_type=FP16` (see https://github.com/openvinotoolkit/openvino_contrib/pull/222). Do you need FP16 on GPU? Because for other hardware targets there is no difference for FP32 and FP16 (CPU converts automatically to FP32 and VPU converts to FP16).

**Comment by jsiebert** [comment]
Hey @dkurt,

ah, sorry... I haven't seen #222 before. I should have searched more extensively for existing tickets.

My goal is to run this model (and other models in the future) on a MyriadX in an OAK-D camera. As far as I understand the MyriadX documentation, the models work best when converted to FP16. Or have I misunderstood something here?

**Comment by dkurt** [comment]
@jsiebert, you can use just FP32 model. Myriad plugin converts it to FP16 anyway.

**Comment by jsiebert** [comment]
Okay, understood! I will close this issue...

Thanks for your support 👍
