### ISSUE TITLE
[ARM plugin] Docker build may fail if RAM allocation is not increased accordingly

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/openvino_contrib#28]
One issue I kept hitting is the OpenVINO compilation fails if we do not provide enough memory for the docker environment. The issue is we are running "make -j" according to the number of available CPUs, and that is dangerous because it can easily throw off the RAM usage. 

***
Approach #1: build OpenCV, OpenVINO and the plugin using pre-configured Dockerfile (cross-compiling, the preferred way)
***

Suggestions: Hard lock the RAM usage by setting the -j to 1 and so it will not fail. Alternatively, document the minimal RAM usage per CPUs, and so the docker environment has to set up to match (and this is "CRITICAL"). Otherwise, we will face random compile error when RAM runs out.

**Comment by terfendail** [comment]
The issue addressed by PR #48

**Comment by alvoron** [comment]
@raymondlo84 Environment variable `BUILD_JOBS ` has been added to control the number of jobs.
