### ISSUE TITLE
PyTorch model conversion failed 

### ISSUE THREAD

**Issue by alvoron** [openvinotoolkit/openvino_contrib#304]
Pytorch model conversion tests are failed in Linux CI:
https://dev.azure.com/openvinoci/dldt/_build/results?buildId=266105&view=logs&j=0609cd82-f9f7-5e70-371c-89fca78031ab&t=1d674d94-b5eb-5999-fed9-1cb906ec0fd4&l=3020

@dkurt @likholat could you please take a look?

**Comment by dkurt** [comment]
solved by https://github.com/openvinotoolkit/openvino_contrib/pull/302
