### ISSUE TITLE
build arm_plugin error on arm64 platform 

### ISSUE THREAD

**Issue by dukezuoHZ** [openvinotoolkit/openvino_contrib#347]
I need run openvino on arm64 platform,so i need build openvino and arm_plugin modules of openvino_contrib,but I met a issue when i built it, anyone can help me?

make[2]: *** No rule to make target '/home/duke/openvino_contrib-master/modules/arm_plugin/thirdparty/ComputeLibrary/SConstruct', needed by 'inference-engine/build-modules/arm_plugin/thirdparty/libarm_compute-static.a'.  Stop.
CMakeFiles/Makefile2:5951: recipe for target 'inference-engine/build-modules/arm_plugin/thirdparty/CMakeFiles/arm_compute_static_libs.dir/all' failed
make[1]: *** [inference-engine/build-modules/arm_plugin/thirdparty/CMakeFiles/arm_compute_static_libs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I config with command : 
sudo cmake -DIE_EXTRA_MODULES=/home/duke/openvino_contrib-master/modules -DBUILD_java_api=OFF -DCMAKE_INSTALL_PREFIX=/opt/intel ..

**Comment by dukezuoHZ** [comment]
sorry,I made a mistake that i didn't  git submodule, but after i do it ,it report another issue:
~~~~~~~~~~~~~~~~~~~~
nknown variables: internal_only
inference-engine/build-modules/arm_plugin/thirdparty/CMakeFiles/arm_compute_static_libs.dir/build.make:1838: recipe for target 'inference-engine/build-modules/arm_plugin/thirdparty/libarm_compute-static.a' failed
make[2]: *** [inference-engine/build-modules/arm_plugin/thirdparty/libarm_compute-static.a] Error 1
CMakeFiles/Makefile2:5951: recipe for target 'inference-engine/build-modules/arm_plugin/thirdparty/CMakeFiles/arm_compute_static_libs.dir/all' failed
make[1]: *** [inference-engine/build-modules/arm_plugin/thirdparty/CMakeFiles/arm_compute_static_libs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by dkurt** [comment]
@dukezuoHZ, can you please clean build folder and retry without `sudo`?

**Comment by dukezuoHZ** [comment]
thanks dkurt,I can build ok now. because some network error some source didn't download finished.
