### ISSUE TITLE
failure to build arm_plugin with exist computeLibrary libs.

### ISSUE THREAD

**Issue by xlla** [openvinotoolkit/openvino_contrib#359]
I have built and installed the computeLibrary libs, then pass the ARM_COMPUTE_INCLUDE_DIR and ARM_COMPUTE_LIB_DIR to cmake, it will found arm_compute libs but failure to found targets "arm_compute::xxx".

the build environment is yocto, target is raspberry aarch64 ARCH, here is the snippets of the log:

<pre>
| -- Inference Engine enabled features:
| --
| --     CI_BUILD_NUMBER: custom_releases/2021/4_c2bfbf29fbc44f9a3c8403d77da5be7e45cbbb4f
| --     ARM_COMPUTE_INCLUDE_DIR = /home/xlla/develop/git/out/linux64/build/tmp/work/aarch64-poky-linux/openvino-inference-engine/2021.4.1-r0/recipe-sysroot/usr/include
| --     ARM_COMPUTE_LIB_DIR = /home/xlla/develop/git/out/linux64/build/tmp/work/aarch64-poky-linux/openvino-inference-engine/2021.4.1-r0/recipe-sysroot/usr/lib
| --     ARM_COMPUTE_TOOLCHAIN_PREFIX =
| --     ARM_COMPUTE_TARGET_ARCH = arm64-v8a
| --     ARM_COMPUTE_SCONS_JOBS =
| --
| -- Using /home/xlla/develop/git/out/linux64/build/tmp/work/aarch64-poky-linux/openvino-inference-engine/2021.4.1-r0/recipe-sysroot/usr/include to include arm compute library headers
| -- Found arm_compute-static: /home/xlla/develop/git/out/linux64/build/tmp/work/aarch64-poky-linux/openvino-inference-engine/2021.4.1-r0/recipe-sysroot/usr/lib/libarm_compute-static.a
| -- Found arm_compute_core-static: /home/xlla/develop/git/out/linux64/build/tmp/work/aarch64-poky-linux/openvino-inference-engine/2021.4.1-r0/recipe-sysroot/usr/lib/libarm_compute_core-static.a
| -- Register template_plugin to be built in build-modules/template_plugin
| -- Found PythonInterp: /home/xlla/develop/git/out/linux64/build/tmp/work/aarch64-poky-linux/openvino-inference-engine/2021.4.1-r0/recipe-sysroot-native/usr/bin/python3-native/python3 (found suitable version "3.8.13", minimum required is "3")
| CMake Warning at cmake/developer_package/shellcheck/shellcheck.cmake:11 (message):
|   shellcheck tool is not found
| Call Stack (most recent call first):
|   CMakeLists.txt:163 (ie_shellcheck_process)
| 
| 
| -- Configuring done
| CMake Error at /home/xlla/develop/git/out/linux64/build/tmp/work/aarch64-poky-linux/openvino-inference-engine/2021.4.1-r0/git/cmake/developer_package/plugins/plugins.cmake:58 (add_library):
|   Target "armPlugin" links to target "arm_compute::arm_compute" but the
|   target was not found.  Perhaps a find_package() call is missing for an
|   IMPORTED target, or an ALIAS target is missing?
| Call Stack (most recent call first):
|   /home/xlla/develop/git/out/linux64/build/tmp/work/aarch64-poky-linux/openvino-inference-engine/2021.4.1-r0/contrib/modules/arm_plugin/src/CMakeLists.txt:18 (ie_add_plugin)

</pre>

**Comment by allnes** [comment]
Hi @xlla 
Our plugin used Arm Compute Library from [3rdparty](https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/arm_plugin/thirdparty) directory.
Set `ARM_COMPUTE_INCLUDE_DIR` and `ARM_COMPUTE_LIB_DIR` don't require.

**Comment by xlla** [comment]
Hi @allnes , I have read it, because Scons build script for compute library is hardly to run on yocto, so it will failure be built by openvino_contrib's 3dparty build task insider openvino's build task.

And I have fix it in my fork.
