### ISSUE TITLE
why arm_plugin does not install itself after being build? 

### ISSUE THREAD

**Issue by xlla** [openvinotoolkit/openvino_contrib#361]
I have built openvino with openvino_contrib successful,  after install the inference-engine to my device, it complain libarmPlugin.so can't be found.

<pre>
rpi4:~$ python3 test/test-opencv-dnn-cpu.py 
[INFO] loading model...
use dnn target cpu...
Traceback (most recent call last):
  File "test/test-opencv-dnn-cpu.py", line 25, in <module>
    preds = net.forward()
cv2.error: OpenCV(4.5.3-openvino) /usr/src/debug/opencv/4.5.2-r0/git/modules/dnn/src/ie_ngraph.cpp:738: error: (-2:Unspecified error) in function 'initPlugin'
> Failed to initialize Inference Engine backend (device = CPU): Failed to create plugin libarmPlugin.so for device CPU
> Please, check your environment
> Cannot load library 'libarmPlugin.so': libarmPlugin.so: cannot open shared object file: No such file or directory
> 

</pre>

then I investigate the whole build and deploy process, I found in my branch the install task inside arm_plugin's CMakeLists.txt was commented, and in master branch those component install task was removed.

**Comment by alvoron** [comment]
@xlla thank you for raising the question.
Could you please point to commented \ deleted lite of code you're referring to?

What contrib branch do you use - master or any release?
