### ISSUE TITLE
arm_plugin compile error

### ISSUE THREAD

**Issue by cslxiao** [openvinotoolkit/openvino_contrib#372]
/usr/bin/ld: ../thirdparty/libarm_compute-static.a(CPPScheduler.o): in function `arm_compute::(anonymous namespace)::Thread::Thread(int)':
CPPScheduler.cpp:(.text._ZN11arm_compute12_GLOBAL__N_16ThreadC2Ei+0x78): undefined reference to `pthread_create'
/usr/bin/ld: CPPScheduler.cpp:(.text._ZN11arm_compute12_GLOBAL__N_16ThreadC2Ei+0x88): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status

Anyone can help? Thanks in advance.

**Comment by adrianboguszewski** [comment]
If you see this error, please edit your CMakeCache.txt file and add -pthread flag to CMAKE_MODULE_LINKER_FLAGS

`CMAKE_MODULE_LINKER_FLAGS:STRING=-pthread`

**Comment by YaroslavSchubert** [comment]
> If you see this error, please edit your CMakeCache.txt file and add -pthread flag to CMAKE_MODULE_LINKER_FLAGS
> 
> `CMAKE_MODULE_LINKER_FLAGS:STRING=-pthread`
> 
> Then compile once again (just run make).

Thanks, worked for me.
