### ISSUE TITLE
openvino build fails for python onnx

### ISSUE THREAD

**Issue by alexein777** [openvinotoolkit/openvino_contrib#374]
I followed the recommended (cross-compiling) build guide and docker image gets created successfully on Raspberry Pi 4 (Raspbian Buster OS). However, when I run

mkdir build
docker container run --rm -ti -v $PWD/build:/arm_cpu_plugin arm-plugin

while building openvino I get the following error:

    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ia0575zc/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ia0575zc/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-i5x424zi/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/onnx
         cwd: /tmp/pip-install-ia0575zc/onnx/
    Complete output (132 lines):
    fatal: not a git repository (or any of the parent directories): .git
    running install
    running build
    running build_py
    running create_version
    running cmake_build
    Using cmake args: ['/usr/local/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/local/include/python3.7m', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-37m-arm-linux-gnueabihf.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/tmp/pip-install-ia0575zc/onnx']
    Generated: /tmp/pip-install-ia0575zc/onnx/.setuptools-cmake-build/onnx/onnx-ml.proto
    Generated: /tmp/pip-install-ia0575zc/onnx/.setuptools-cmake-build/onnx/onnx-operators-ml.proto
    Generated: /tmp/pip-install-ia0575zc/onnx/.setuptools-cmake-build/onnx/onnx-data.proto
    CMake Warning at CMakeLists.txt:451 (find_package):
      By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "pybind11",
      but CMake did not find one.
    
      Could not find a package configuration file provided by "pybind11"
      (requested version 2.2) with any of the following names:
    
        pybind11Config.cmake
        pybind11-config.cmake
    
      Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
      "pybind11_DIR" to a directory containing one of the above files.  If
      "pybind11" provides a separate development package or SDK, be sure it has
      been installed.
    
    
    --
    -- ******** Summary ********
    --   CMake version             : 3.13.4
    --   CMake command             : /usr/local/bin/cmake
    --   System                    : Linux
    --   C++ compiler              : /usr/bin/c++
    --   C++ compiler version      : 8.3.0
    --   CXX flags                 :  -Wnon-virtual-dtor
    --   Build type                : Release
    --   Compile definitions       : __STDC_FORMAT_MACROS
    --   CMAKE_PREFIX_PATH         :
    --   CMAKE_INSTALL_PREFIX      : /usr/local
    --   CMAKE_MODULE_PATH         :
    --
    --   ONNX version              : 1.11.0
    --   ONNX NAMESPACE            : onnx
    --   ONNX_USE_LITE_PROTO       : OFF
    --   USE_PROTOBUF_SHARED_LIBS  : OFF
    --   Protobuf_USE_STATIC_LIBS  : ON
    --   ONNX_DISABLE_EXCEPTIONS   : OFF
    --   ONNX_WERROR               : OFF
    --   ONNX_BUILD_TESTS          : OFF
    --   ONNX_BUILD_BENCHMARKS     : OFF
    --   ONNXIFI_DUMMY_BACKEND     : OFF
    --   ONNXIFI_ENABLE_EXT        : OFF
    --
    --   Protobuf compiler         : /usr/bin/protoc
    --   Protobuf includes         : /usr/include
    --   Protobuf libraries        : /usr/lib/arm-linux-gnueabihf/libprotobuf.a;-lpthread
    --   BUILD_ONNX_PYTHON         : ON
    --     Python version        :
    --     Python executable     : /usr/bin/python3
    --     Python includes       : /usr/local/include/python3.7m
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-install-ia0575zc/onnx/.setuptools-cmake-build
    make[3]: warning: -j4 forced in submake: resetting jobserver mode.
    [  2%] Built target onnxifi_dummy
    [  5%] Built target onnxifi_loader
    [  8%] Built target gen_onnx_proto
    [ 11%] Built target onnxifi_wrapper
    [ 14%] Built target gen_onnx_data_proto
    [ 16%] Built target gen_onnx_operators_proto
    [ 30%] Built target onnx_proto
    [ 97%] Built target onnx
    [ 98%] Linking CXX shared module onnx_cpp2py_export.cpython-37m-arm-linux-gnueabihf.so
    /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0x6bc): R_ARM_TLS_LE32 relocation not permitted in shared object
    /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::Init()':
    (.text+0x6bc): dangerous relocation: unsupported relocation
    /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0x758): R_ARM_TLS_LE32 relocation not permitted in shared object
    /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::GetSerialArenaFallback(void*)':
    (.text+0x758): dangerous relocation: unsupported relocation
    /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0x79c): R_ARM_TLS_LE32 relocation not permitted in shared object
    /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::GetSerialArena()':
    (.text+0x79c): dangerous relocation: unsupported relocation
    /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0x96c): R_ARM_TLS_LE32 relocation not permitted in shared object
    /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::AllocateAligned(unsigned int)':
    (.text+0x96c): dangerous relocation: unsupported relocation
    /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0xba8): R_ARM_TLS_LE32 relocation not permitted in shared object
    /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::AllocateAlignedAndAddCleanup(unsigned int, void (*)(void*))':
    (.text+0xba8): dangerous relocation: unsupported relocation
    /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o)(.text+0xc40): R_ARM_TLS_LE32 relocation not permitted in shared object
    /usr/bin/ld: /usr/lib/arm-linux-gnueabihf/libprotobuf.a(arena.o): in function `google::protobuf::internal::ArenaImpl::AddCleanup(void*, void (*)(void*))':
    (.text+0xc40): dangerous relocation: unsupported relocation
    collect2: error: ld returned 1 exit status
    make[5]: *** [CMakeFiles/onnx_cpp2py_export.dir/build.make:88: onnx_cpp2py_export.cpython-37m-arm-linux-gnueabihf.so] Error 1
    make[4]: *** [CMakeFiles/Makefile2:357: CMakeFiles/onnx_cpp2py_export.dir/all] Error 2
    make[3]: *** [Makefile:130: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ia0575zc/onnx/setup.py", line 358, in <module>
        'backend-test-tools = onnx.backend.test.cmd_tools:main',
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-ia0575zc/onnx/setup.py", line 232, in run
        self.run_command('cmake_build')
      File "/usr/local/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-ia0575zc/onnx/setup.py", line 226, in run
        subprocess.check_call(build_args)
      File "/usr/local/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '4']' returned non-zero exit status 2.
    ----------------------------------------
[ 16%] [cpplint] /arm_cpu_plugin/openvino/src/tests/ie_test_utils/common_test_utils/ngraph_test_utils.hpp
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ia0575zc/onnx/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ia0575zc/onnx/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-i5x424zi/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/onnx Check the logs for full command output.

How can I solve this?

**Comment by alvoron** [comment]
@alexein777 
What OS do use use on Raspberry? Could you please try to install pybinf11 package from system repository?
If you're using Ubuntu the command is `apt-get install python-pybind11`

**Comment by ilya-lavrenov** [comment]
@alexein777 from the logs it seems that you are building with system protobuf (OpenVINO's cmake option `-DENABLE_SYSTEM_PROTOBUF`), is there any need in it? System static protobuf library is compiled without `-fPIC` and cannot be used with OpenVINO. 
Also, have you used docker files from https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/arm_plugin/dockerfiles to build docker image? or custom one? could you please share it in later case?
