### ISSUE TITLE
Use arm with python 

### ISSUE THREAD

**Issue by andriyrizhiy** [openvinotoolkit/openvino_contrib#375]
Hi! I want to build and use openvino in mac os with m1 CPU. So, I use this instruction: https://github.com/openvinotoolkit/openvino_contrib/wiki/How-to-build-ARM-CPU-plugin. After building i run setupvars.sh in install_ie folder. But it is not founded python:
```
[setupvars.sh] WARNING: Can not find OpenVINO Python binaries by path /Users/rizhiy/Downloads/openvino_builds/install_ie/python
[setupvars.sh] WARNING: OpenVINO Python environment does not set properly
[setupvars.sh] OpenVINO environment initialized
```
Сan anyone help with this?

**Comment by alvoron** [comment]
@andriyrizhiy the instruction you're referring to has been significantly changed recently.
Could you please try a new version of instructinon?

Be the way, python environment is required only if you need to develop python applications. If you develop or run C++ applications you may skip this warning.
