### ISSUE TITLE
Demo for Java API v2.0?

### ISSUE THREAD

**Issue by xuanqing94** [openvinotoolkit/openvino_contrib#398]
Hi, thanks for the great work of Java API. I am able to follow the examples in compatibility mode. But since it is deprecated, could you also provide some examples in API 2.0? Right now I only see some simple usages under unit test folder.

**Comment by dkurt** [comment]
Hi! You may find this useful: https://github.com/dkurt/qupath-extension-openvino/blob/main/src/main/java/qupath/ext/openvino/OpenVINOBundle.java.

@likholat, can you please handle this issue and update Java samples?

**Comment by dkurt** [comment]
Please take a look at updated sample https://github.com/openvinotoolkit/openvino_contrib/blob/master/modules/java_api/samples/face_detection_java_sample

**Comment by alvoron** [comment]
@xuanqing94 does this sample work to you?

**Comment by xuanqing94** [comment]
I haven't given a try but it looks good. I wrote something similar in my own codebase last month.
