### ISSUE TITLE
Slow model execution (aarch64)

### ISSUE THREAD

**Issue by MdScntst** [openvinotoolkit/openvino_contrib#412]
Hello. I'm trying to figure out why IR model executes much slower (up to 5-6 times) than  .onnx version (using onnxruntime backend).
HW: CPU rockchip rk3399. The model was converted using --use_legacy_frontend flag, overwise [Node input index is out of range](https://github.com/openvinotoolkit/openvino/issues/12476) 
Sample code is attached.
[Samples.zip](https://github.com/openvinotoolkit/openvino_contrib/files/9443654/Samples.zip)

**Comment by alvoron** [comment]
@MdScntst could you please set `_dump` variable to `true` on this line: https://github.com/openvinotoolkit/openvino_contrib/blob/9d729cf0f9e73aa318b38af408b6c385a5300dc6/modules/arm_plugin/src/transformations/arm_optimizations.hpp#L21
then infer the network and share *.dot files generated by the plugin with us (it you have a right to share the network) or analyze it by yourself via graphviz tool.
Some operations are executed by non-optimized OpenVINO reference code. Such operations are marked as `Supported**` (with two asterisks) in this doc: https://github.com/openvinotoolkit/openvino_contrib/wiki/ARM-plugin-operation-set-specification
I suspect some operations used in your network are non-optimized. Could you please confirm that?

**Comment by alvoron** [comment]
@MdScntst did you have a chance to review the final graph and operations?

**Comment by thusinh1969** [comment]
It is SLOW ...on Raspberry PI 4. Yolov5n same model with SparseML quant-aware training + DeepSparse costs 237ms while on pure Openvino ARM64 is 1 second !!!
