### ISSUE TITLE
Use static library with onnxruntime build

### ISSUE THREAD

**Issue by venki-thiyag** [openvinotoolkit/openvino_contrib#430]
I have built static library of OpenVino using the following command:

`cmake -DENABLE_IR_V7_READER=OFF -DENABLE_ONEDNN_FOR_GPU=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/mt.runtime.win32.toolchain.cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release ..
`
and

`cmake --build . --target openvino --config Release -j12`

I have the output libs in <openvino_src_dir>\bin\intel64\Release

Now we need to build onnxruntime with this output, I am unable to find any steps. Looks like we need to run setupvars.bat but looks like output folder needs to be in some structure and not sure what all files needs to be in that.

Steps for building onnxruntime with OpenVino was referred here:
https://onnxruntime.ai/docs/execution-providers/OpenVINO-ExecutionProvider.html
But doesn't specify about custom build in OpenVino.

Can I get some help here?

**Comment by ilya-lavrenov** [comment]
Hi,

The guide how to build and use static libraries is here https://github.com/openvinotoolkit/openvino/wiki/StaticLibraries#build-static-openvino-libraries. The procedure is simple and the same as for dynamic libraries:
1. Build OV
2. Install
3. Build another app against static / dynamic libraries

Once more about installation from common build pipeline https://github.com/openvinotoolkit/openvino/wiki/BuildingCode#installing

**Comment by alvoron** [comment]
@venki-thiyag did the suggestion provided by Ilya help you?

**Comment by venki-thiyag** [comment]
Yes, I was able to build static version of OpenVino, but we have changed strategy to use dynamic version itself. Thanks for the support.
