### ISSUE TITLE
ImportError: libpython3.7m.so.1.0: cannot open shared object file

### ISSUE THREAD

**Issue by mio903061** [openvinotoolkit/openvino_contrib#440]
Hi!
I was trying to inference with ARM CPU and follow the step of [Building ARM CPU plugin with LINUX](https://github.com/openvinotoolkit/openvino_contrib/wiki/How-to-build-ARM-CPU-plugin#building-for-linux).  

However, when I try to build a Docker image with `docker image build -t arm-plugin -f dockerfiles/Dockerfile.RPi64_focal .` , I faced the error 

### Error  
```
        esac; \
         _PYTHON_PROJECT_BASE=/Python-3.7.9 _PYTHON_HOST_PLATFORM=linux-aarch64 PYTHONPATH=/Python-3.7.9/build/lib.linux-aarch64-3.7:./Lib _PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_m_linux_aarch64-linux-gnu python3.7 -m ensurepip \
                $ensurepip --root=/ ; \
fi
Traceback (most recent call last):
  File "/Python-3.7.9/Lib/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Python-3.7.9/Lib/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Python-3.7.9/Lib/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Python-3.7.9/Lib/ensurepip/__init__.py", line 6, in <module>
    import tempfile
  File "/Python-3.7.9/Lib/tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "/Python-3.7.9/Lib/random.py", line 42, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
make: *** [Makefile:1151: altinstall] Error 1
```

### My environment is 
Raspberry PI 4G 
Ubuntu20.04 (64bit)
Docker version 20.10.18, build b40c2f6

### Cause  
It seems that Python-3.7.9.tar.xz doesn't include `libpython3.7m.so.1.0` from the begining.  
(https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tar.xz)  

### Questions  
How can I install `libpython3.7m.so.1.0` mannually?  

Please help me if you know any solutions.  

Thanks.

**Comment by ilya-lavrenov** [comment]
Hi @mio903061 
I've updated build process and dockerfiles. Could you please try this PR https://github.com/openvinotoolkit/openvino_contrib/pull/447? 
```bash
git remote add ilya-lavrenov https://github.com/ilya-lavrenov/openvino_contrib.git
git fetch ilya-lavrenov
git checkout docker-build-update
```
And all others as usual
