### ISSUE TITLE
Any chance to support GatherNd and GatherNd_1in the future?

### ISSUE THREAD

**Issue by tankienleong** [openvinotoolkit/openvino_contrib#494]
Raspberry pi 4
Ubuntu 20.04 arm64
Openvino 2022.3

Hi, I was able to compile the ARM CPU plugin successfully but when I run my inference code it shows RuntimeError: Arm Plugin: Nodes from snapshot are not supported by the plugin: GatherNd (GatherND.opset8) GatherNd_1 (GatherND.opset8)

I read the [https://github.com/openvinotoolkit/openvino_contrib/wiki/ARM-plugin-operation-set-specification](url), just wondering if is there any chance you guys will support these two nodes in the future.

Thank you.

**Comment by allnes** [comment]
Hi, @tankienleong 
Could you share with us IR model which you run infer that we can check this problem

**Comment by tankienleong** [comment]
[ir_model.zip](https://github.com/openvinotoolkit/openvino_contrib/files/10175632/ir_model.zip)

Hi, @allnes
Sure. Thank you.

**Comment by allnes** [comment]
@tankienleong hi
I'm sorry for delay. We prepared [PR](https://github.com/openvinotoolkit/openvino_contrib/pull/522) with fix. Please check.

**Comment by tankienleong** [comment]
Hi @allnes 
![Screenshot from 2022-12-21 08-38-47](https://user-images.githubusercontent.com/25731934/208793782-ef2d729b-a846-4b3b-b2f9-3229e11effba.png)

Error occur during the compilation.

CPPScheduler.cpp:(.text._ZN11arm_compute12_GLOBAL__N_16ThreadC2Ei+0x78): undefined reference to `pthread_create'

Please let me know if you need more info.

**Comment by tankienleong** [comment]
I manage to complete the compilation after edit the CMakeCache.txt file and add -pthread flag to CMAKE_MODULE_LINKER_FLAGS

**Comment by tankienleong** [comment]
Hi @allnes 

I am able to run inference with the ARM plugin. 

Thank you so much for your help.
