### ISSUE TITLE
[NVIDIA] Failed inference on OMZ models

### ISSUE THREAD

**Issue by dkurt** [openvinotoolkit/openvino_contrib#520]
Hi! I did some analysis of [OMZ](https://github.com/openvinotoolkit/open_model_zoo/) models and found the following issues using [NVIDIA plugin](https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/nvidia_plugin). Hope it might be helpful.

| Model name | Error |
|---|---|
|asl-recognition-0004<br>common-sign-language-0002|[ ERROR ] /content/openvino_contrib/modules/nvidia_plugin/src/ops/subgraph.cpp:59(initExecuteSequence): Node: name = Sqrt_4372, description = Sqrt; Is not found in OperationRegistry|
|bert-large-uncased-whole-word-masking-squad-0001<br>bert-large-uncased-whole-word-masking-squad-emb-0001<br>bert-small-uncased-whole-word-masking-squad-0001<br>bert-small-uncased-whole-word-masking-squad-0002|[ ERROR ] /content/openvino_contrib/modules/nvidia_plugin/src/cuda_plugin.cpp:74(LoadExeNetworkImpl): Input format 72 is not supported yet. Supported formats are: FP32, FP16, I32, I16, I8, U8 and BOOL.|
|face-detection-0205<br>face-detection-0206<br>horizontal-text-detection-0001<br>instance-segmentation-person-0007<br>instance-segmentation-security-0002<br>instance-segmentation-security-0091<br>instance-segmentation-security-0228<br>instance-segmentation-security-1039<br>instance-segmentation-security-1040<br>machine-translation-nar-de-en-0002<br>machine-translation-nar-en-de-0002<br>machine-translation-nar-en-ru-0002<br>machine-translation-nar-ru-en-0002<br>person-detection-0106<br>person-detection-0203<br>person-detection-0301<br>person-detection-0302<br>person-detection-0303<br>person-vehicle-bike-detection-2003<br>person-vehicle-bike-detection-2004<br>semantic-segmentation-adas-0001|[ ERROR ] /content/openvino_contrib/modules/nvidia_plugin/src/cuda_plugin.cpp:60(LoadExeNetworkImpl): Output format 72 is not supported yet. Supported formats are: FP32, FP16, I32, I16, I8, U8 and BOOL.|
|facial-landmarks-98-detection-0001<br>human-pose-estimation-0005<br>human-pose-estimation-0006<br>human-pose-estimation-0007<br>icnet-camvid-ava-0001<br>icnet-camvid-ava-sparse-30-0001<br>icnet-camvid-ava-sparse-60-0001<br>road-segmentation-adas-0001|[ ERROR ] /content/openvino_contrib/modules/nvidia_plugin/src/ops/interpolate.cpp:62(interpolateFactory): Interpolate node is not supported: not implemented. |
|faster-rcnn-resnet101-coco-sparse-60-0001<br>person-detection-retail-0002|[ ERROR ] /content/openvino_contrib/modules/nvidia_plugin/src/ops/subgraph.cpp:59(initExecuteSequence): Node: name = Proposal_4852, description = Proposal; Is not found in OperationRegistry|
|human-pose-estimation-0001<br>person-vehicle-bike-detection-crossroad-0078<br>time-series-forecasting-electricity-0001|[ ERROR ] /content/openvino_contrib/modules/nvidia_plugin/src/ops/subgraph.cpp:59(initExecuteSequence): Node: name = Elu_2781, description = Elu; Is not found in OperationRegistry|
|license-plate-recognition-barrier-0001|[ ERROR ] /content/openvino_contrib/modules/nvidia_plugin/src/ops/subgraph.cpp:59(initExecuteSequence): Node: name = Tile_2031, description = Tile; Is not found in OperationRegistry|
|person-detection-action-recognition-0005<br>person-detection-action-recognition-teacher-0002<br>person-detection-raisinghand-recognition-0001<br>person-detection-action-recognition-0006|[ ERROR ] /content/openvino_contrib/modules/nvidia_plugin/src/ops/subgraph.cpp:59(initExecuteSequence): Node: name = NormalizeL2_9411, description = NormalizeL2; Is not found in OperationRegistry|
|person-detection-asl-0001|[ ERROR ] /content/openvino_contrib/modules/nvidia_plugin/src/cuda_executable_network.cpp:59(ExecutableNetwork): Standard exception from compilation library: get_shape was called on a descriptor::Tensor with dynamic shape|
|person-vehicle-bike-detection-crossroad-yolov3-1020<br>yolo-v2-tiny-ava-0001<br>yolo-v2-tiny-ava-sparse-30-0001<br>yolo-v2-tiny-ava-sparse-60-0001<br>yolo-v2-tiny-vehicle-detection-0001|[ ERROR ] /content/openvino_contrib/modules/nvidia_plugin/src/ops/subgraph.cpp:59(initExecuteSequence): Node: name = RegionYolo_4660, description = RegionYolo; Is not found in OperationRegistry|
|smartlab-sequence-modelling-0001|[ ERROR ] /content/openvino_contrib/modules/nvidia_plugin/src/ops/subgraph.cpp:59(initExecuteSequence): Node: name = HardSigmoid_2960, description = HardSigmoid; Is not found in OperationRegistry|
|unet-camvid-onnx-0001|[ ERROR ] /content/openvino_contrib/modules/nvidia_plugin/src/ops/subgraph.cpp:59(initExecuteSequence): Node: name = Exp_2112, description = Exp; Is not found in OperationRegistry|
|yolo-v2-ava-0001<br>yolo-v2-ava-sparse-35-0001<br>yolo-v2-ava-sparse-70-0001|[ ERROR ] /content/openvino_contrib/modules/nvidia_plugin/src/ops/subgraph.cpp:59(initExecuteSequence): Node: name = ExtractImagePatches_2200, description = ExtractImagePatches; Is not found in OperationRegistry|

**Comment by nkogteva** [comment]
Please check NVIDIA plugin limitations. List of supported operations https://github.com/openvinotoolkit/openvino_contrib/blob/master/modules/nvidia_plugin/docs/cuda_opset.md
