### ISSUE TITLE
GetCore1: Can't get absolute file path libopenvino.so

### ISSUE THREAD

**Issue by tamnguyenvan** [openvinotoolkit/openvino_contrib#549]
Thank you for this amazing work.
I got that error when I'm following this article. https://medium.com/@dmitry.kurtaev/audio-recognition-in-android-with-openvino-5d51e71f1426

![image](https://user-images.githubusercontent.com/16330538/211228910-6fc2025f-337b-4772-a3e2-875ca6ecb6b4.png)

**Comment by dkurt** [comment]
Let's keep only one issue per problem, this or https://github.com/dkurt/openvino_java/issues/18.
