### ISSUE TITLE
Build arm plugin falied while building onnx.

### ISSUE THREAD

**Issue by Yastruhank** [openvinotoolkit/openvino_contrib#619]
I use the docker file Dockerfile.RPi64_focal and follow the Approach #1 in the wiki to build the openvino arm plugin.
But I got a error while building onnx in openvino.The error imformation are post below.

Processing /arm_cpu_plugin/openvino/thirdparty/onnx/onnx/onnx/onnx.in.proto
Writing /arm_cpu_plugin/openvino/build/thirdparty/onnx/onnx/onnx/onnx_openvino_onnx-ml.proto
Writing /arm_cpu_plugin/openvino/build/thirdparty/onnx/onnx/onnx/onnx_openvino_onnx-ml.proto3
Writing /arm_cpu_plugin/openvino/build/thirdparty/onnx/onnx/onnx/onnx-ml.pb.h
generating /arm_cpu_plugin/openvino/build/thirdparty/onnx/onnx/onnx/onnx_pb.py
[ 15%] Running C++ protocol buffer compiler on /arm_cpu_plugin/openvino/build/thirdparty/onnx/onnx/onnx/onnx_openvino_onnx-ml.proto
/bin/sh: 1: ../../protobuf/install/bin/protoc: Exec format error
make[2]: *** [thirdparty/onnx/onnx/CMakeFiles/gen_onnx_proto.dir/build.make:74: thirdparty/onnx/onnx/onnx/onnx_openvino_onnx-ml.pb.cc] Error 2
make[1]: *** [CMakeFiles/Makefile2:3218: thirdparty/onnx/onnx/CMakeFiles/gen_onnx_proto.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by alvoron** [comment]
Hi @Yastruhank 
Thank you for submitting the issue! What `openvino_contrib` baseline do you use - the latest master or release?
If you're using master - could you please repeat your exercise on 22.3 baseline?

**Comment by alvoron** [comment]
@Yastruhank the team has completed migration of ARM functionality into CPU plugin hosted in the main repo: https://github.com/openvinotoolkit/openvino/tree/master/src/plugins/intel_cpu
(it still named as Intel CPU plugin however it supports both x86 and ARM architectures now).
We're going to stop maintenance of "old" ARM plugin hosted in contrib repository, it's going to be removed soon.

Could you please try to reproduce the issue using "new" CPU plugin from main OpenVINO repository?

**Comment by alvoron** [comment]
@Yastruhank I closed the ticket since no response. Please feel free to try Intel CPU plugin on ARM platform and share your experience.
