### ISSUE TITLE
Arm plugin build failed while native compiling

### ISSUE THREAD

**Issue by Dev-Divyendh** [openvinotoolkit/openvino_contrib#622]
I'm using openvino 2022.1 on raspbian buster os,  I tried following this link to build arm plugin:
[https://github.com/openvinotoolkit/openvino_contrib/wiki/How-to-build-ARM-CPU-plugin](https://github.com/openvinotoolkit/openvino_contrib/wiki/How-to-build-ARM-CPU-plugin)
I tried the third , native compilation method.
I cloned '2022/1' branch of openvino_contrib and used it.

Got the following cmake error:

[100%] Linking CXX shared module /home/pi/openvino/bin/armv7l/Release/lib/libopenvino_arm_cpu_plugin.so
usr/bin/ld: ../thirdparty/libarm_compute-static.a(CPPScheduler.o): in function `arm_compute::(anonymous namespace)::Thread::Thread(int)':
CPPScheduler.cpp:(.text._ZN11arm_compute12_GLOBAL__N_16ThreadC2Ei+0xf8): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/openvino_arm_cpu_plugin.dir/build.make:2137: /home/pi/openvino/bin/armv7l/Release/lib/libopenvino_arm_cpu_plugin.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:362: src/CMakeFiles/openvino_arm_cpu_plugin.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

kindly help to resolve the issue.

**Comment by ilya-lavrenov** [comment]
Could you please try latest master branch?
The fix for the similar problems is applied in https://github.com/openvinotoolkit/openvino_contrib/pull/603

**Comment by Dev-Divyendh** [comment]
I'm using openvino 2022.1.0 inorder to use Intel Movidius VPU, but the latest master branch is compatible with openvino 2022.3.0.
So are there any other soutions?

**Comment by ilya-lavrenov** [comment]
You can backport that fix to 2022.1 branch.

**Comment by Dev-Divyendh** [comment]
I have backported the fix to 2022.1 and the build was successful.
We built the open zoo model using the link:
[https://www.intel.in/content/www/in/en/support/articles/000055510/boards-and-kits/neural-compute-sticks.html]
and the build was successful.

But while running object_detection_demo for Python using CPU using the code:

python3 object_detection_demo.py -i ~/Downloads/person-bicycle-car-detection.mp4 -m ~/Downloads/person-vehicle-bike-detection-crossroad-0078.xml -at ssd -d CPU

We are getting the following error:

[ INFO ] OpenVINO Runtime
[ INFO ] 	build: custom_HEAD_cdb9bec7210f8c24fde3e416c7ada820faaaa23e
[ INFO ] Reading model /home/pi/Downloads/person-vehicle-bike-detection-crossroad-0078.xml
[ WARNING ] The parameter "input_size" not found in SSD wrapper, will be omitted
[ DEBUG ] 	Using SSD model with single output parser
[ INFO ] 	Input layer: data, shape: [1, 3, 1024, 1024], precision: f32, layout: NCHW
[ INFO ] 	Output layer: detection_out, shape: [1, 1, 200, 7], precision: f32, layout: 
Traceback (most recent call last):
  File "object_detection_demo.py", line 298, in <module>
    sys.exit(main() or 0)
  File "object_detection_demo.py", line 183, in main
    detector_pipeline = AsyncPipeline(model)
  File "/home/pi/open_model_zoo/demos/common/python/openvino/model_zoo/model_api/pipelines/async_pipeline.py", line 86, in __init__
    self.model.load()
  File "/home/pi/open_model_zoo/demos/common/python/openvino/model_zoo/model_api/models/model.py", line 173, in load
    self.model_adapter.load_model()
  File "/home/pi/open_model_zoo/demos/common/python/openvino/model_zoo/model_api/adapters/openvino_adapter.py", line 65, in load_model
    self.compiled_model = self.core.compile_model(self.model, self.device, self.plugin_config)
  File "/home/pi/openvino_dist/python/python3.7/openvino/runtime/ie_api.py", line 266, in compile_model
    super().compile_model(model, device_name, {} if config is None else config)
RuntimeError: Device with "CPU" name is not registered in the InferenceEngine

kindly help to resolve the issue.

**Comment by ilya-lavrenov** [comment]
is plugin located in the case folder as libopenvino.so?

**Comment by Dev-Divyendh** [comment]
The plugin is located at:
pi@raspberrypi:~/openvino_contrib/modules/arm_plugin/build 

pi@raspberrypi:~ $ find /home -name libopenvino.so
/home/pi/openvino/bin/armv7l/Release/lib/libopenvino.so
/home/pi/openvino_dist/runtime/lib/armv7l/libopenvino.so

**Comment by Dev-Divyendh** [comment]
I tried using the following cmake command:

cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/pi/openvino_dist -DENABLE_INTEL_MYRIAD=ON -DENABLE_INTEL_CPU=OFF -DENABLE_INTEL_GPU=OFF -DENABLE_CLDNN=OFF -DENABLE_AUTO=OFF -DENABLE_MULTI=OFF -DENABLE_HETERO=OFF -DENABLE_TEMPLATE=OFF -DENABLE_TESTS=OFF -DENABLE_OV_ONNX_FRONTEND=OFF -DENABLE_OV_PADDLE_FRONTEND=OFF -DENABLE_OV_TF_FRONTEND=OFF -DENABLE_NCC_STYLE=OFF -DENABLE_SSE42=OFF -DTHREADING=SEQ -DENABLE_OPENCV=OFF -DENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=$(which python3.7) -DPYTHON_LIBRARY=/usr/lib/arm-linux-gnueabihf/libpython3.7m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.7 ..

Should I add this cmake flag before building:
-DOPENVINO_EXTRA_MODULES=<OPENVINO_CONTRIB_PATH>/openvino_contrib/modules/arm_plugin

If yes , should I build the arm plugin before or after building openvino
Kindly help resolve this issue.

**Comment by ilya-lavrenov** [comment]
> should I build the arm plugin before or after building openvino

ARM plugin cannot be built before OpenVINO, because it depends on it.

There are two approaches.
- Build OpenVINO first, ARM plugin on top of it using `-DOpenVINODeveloperPackage_DIR` for ARM plugin cmake's call
- Build OpenVINO together with ARM plugin using `-DOPENVINO_EXTRA_MODULES`, so the OpenVINO build itself and extra modules (ARM plugin in our case)

Once you build using one of two approaches, you are recommended to install the project(s) into `CMAKE_INSTALL_PREFIX`. Once it's done, you can source `setupvar.sh` from installation folder and use python from `<install>/python` sub-folder.

**Comment by ashwanth-07** [comment]
I did build ARM plugin using -DInferenceEngineDeveloperPackage_DIR after building openvino,  but i got the following error:
RuntimeError: Device with "CPU" name is not registered in the InferenceEngine

**Comment by ilya-lavrenov** [comment]
Maybe you have built and installed OpenVINO first, then ARM plugin?
The proper order:
- Build OpenVINO
- Build ARM plugin
- Then install OpenVINO, install ARM plugin.

If you build and installed OpenVINO, then the same steps for ARM plugin, then `plugins.xml` is not updated during ARM plugin build, because it's already installed.
Please, find and look inside `plugins.xml`

**Comment by ashwanth-07** [comment]
I built openvino and ARM plugin together using the second approach, using -DIE_EXTRA_MODULES, but it shows the following error for object detection using open model zoo:
RuntimeError: Arm Plugin: Nodes from RMNet_SSD are not supported by plugin:
	mbox_conf_softmax (Softmax.0)
	detection_out (DetectionOutput.0)

**Comment by Dev-Divyendh** [comment]
I built openvino and ARM plugin together using the second approach, using -DIE_EXTRA_MODULES, but it shows the following error for object detection using open model zoo:
RuntimeError: Arm Plugin: Nodes from RMNet_SSD are not supported by plugin:
mbox_conf_softmax (Softmax.0)
detection_out (DetectionOutput.0)

**Comment by Dev-Divyendh** [comment]
By changing the model from ssd to yolo using the following command:
python3 object_detection_demo.py -i ~/Downloads/person-bicycle-car-detection.mp4 -m ~/Downloads/person-vehicle-bike-detection-crossroad-yolov3-1020.xml -at yolo -d CPU

Got this error:
Traceback (most recent call last):
  File "object_detection_demo.py", line 298, in <module>
    sys.exit(main() or 0)
  File "object_detection_demo.py", line 183, in main
    detector_pipeline = AsyncPipeline(model)
  File "/home/pi/.local/lib/python3.7/site-packages/openvino/model_zoo/model_api/pipelines/async_pipeline.py", line 86, in __init__
    self.model.load()
  File "/home/pi/.local/lib/python3.7/site-packages/openvino/model_zoo/model_api/models/model.py", line 173, in load
    self.model_adapter.load_model()
  File "/home/pi/.local/lib/python3.7/site-packages/openvino/model_zoo/model_api/adapters/openvino_adapter.py", line 66, in load_model
    self.async_queue = AsyncInferQueue(self.compiled_model, self.max_num_requests)
RuntimeError: std::bad_alloc

Kindly help resolve this issue.
Or is there a model specific for object detection model to run on arm cpu.

**Comment by alvoron** [comment]
@Dev-Divyendh could you try other yolo models available in OMZ?
https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/yolo-v3-tiny-onnx
https://github.com/openvinotoolkit/open_model_zoo/tree/master/models/public/yolo-v4-tiny-tf

**Comment by alvoron** [comment]
@Dev-Divyendh the team has completed migration of ARM functionality into CPU plugin hosted in the main repo: https://github.com/openvinotoolkit/openvino/tree/master/src/plugins/intel_cpu
(it still named as Intel CPU plugin however it supports both x86 and ARM architectures now).
We're going to stop maintenance of "old" ARM plugin hosted in contrib repository, it's going to be removed soon.

Could you please try to reproduce the issue using "new" CPU plugin from main OpenVINO repository?

**Comment by alvoron** [comment]
@Dev-Divyendh I closed the ticket since no response. Please feel free to try Intel CPU plugin on ARM platform and share your experience.
