### ISSUE TITLE
Android model loading and inference example in java/kotlin?

### ISSUE THREAD

**Issue by cuiyuming** [openvinotoolkit/openvino_contrib#633]
Could you provide more detail about model loading and inference in the following tutorial?
https://github.com/openvinotoolkit/openvino_contrib/wiki/How-to-build-ARM-CPU-plugin#building-for-android-os

**Comment by carun** [comment]
I looked at README.md at https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/arm_plugin/demos/coco_detection_android_demo.

The doc mentions about
> Please confirm that your plugins.xml in $WORK_DIR/openvino_install/runtime/lib/aarch64 contains plugin name "CPU".

But this file isn't found.

A working example would help a lot. Thanks!

**Comment by alvoron** [comment]
I believe we may close this ticket since we are discussing your issues https://github.com/openvinotoolkit/openvino_contrib/issues/634 and https://github.com/openvinotoolkit/openvino_contrib/issues/642

Please reopen this ticket if it is still valid and does not duplicate these two.
Thank you!
