### ISSUE TITLE
Java tests failed on macOS x86

### ISSUE THREAD

**Issue by ilya-lavrenov** [openvinotoolkit/openvino_contrib#641]
https://dev.azure.com/openvinoci/dldt/_build/results?buildId=532803&view=logs&jobId=6c23757f-dbf6-510b-3bd6-0534daaa0edf&j=6c23757f-dbf6-510b-3bd6-0534daaa0edf&t=c8ed29ce-b8ce-56bc-1bcc-381212a08266

**Comment by ngaloppo** [comment]
Perhaps RPATH isn't set correctly when building `openvino_contrib`? @ilya-lavrenov how do we do this for openvino samples?

**Comment by ilya-lavrenov** [comment]
RPATHs are not needed during the build. Cmake files stores all information
During samples build we use OpenVINO_DIR env vars set by setupvars.sh

**Comment by ngaloppo** [comment]
This is not a build error, it's a runtime error. More specifically Java related. Does the JVM / Java runtime pick up environment variables set by setupvars.sh on MacOS?

**Comment by dkurt** [comment]
There is definitely one issue with TBB detection: https://github.com/openvinotoolkit/openvino_contrib/blob/a25726a04e8ff57708cd5f8a49a3977186214430/modules/java_api/build.gradle#L27

2022.3: https://storage.openvinotoolkit.org/repositories/openvino/packages/2022.3/macos/m_openvino_toolkit_macos_10_15_2022.3.0.9052.9752fafe8eb_x86_64.tgz
```
$ tree runtime/3rdparty/tbb/
runtime/3rdparty/tbb/
├── LICENSE
├── cmake
│   ├── TBBConfig.cmake
│   └── TBBConfigVersion.cmake
├── include
└── lib
    ├── libtbb.dylib
...
```

But

2023.0: https://storage.openvinotoolkit.org/repositories/openvino/packages/master/2023.0.0.dev20230407/m_openvino_toolkit_macos_10_15_2023.0.0.dev20230407_x86_64.tgz
```
$ tree runtime/3rdparty/tbb/
runtime/3rdparty/tbb/
├── LICENSE
├── include
└── lib
    ├── cmake
    │   └── TBB
    │       ├── TBBConfig.cmake
    │       ├── TBBConfigVersion.cmake
    │       ├── TBBTargets-debug.cmake
    │       ├── TBBTargets-release.cmake
    │       └── TBBTargets.cmake
    ├── libtbb.dylib -> libtbb.12.dylib
...
```
So now it should be something like
```gradle
def native_resources = [
    System.getenv('INTEL_OPENVINO_DIR') + "/runtime/lib/intel64",  // UNIX
    System.getenv('INTEL_OPENVINO_DIR') + "/runtime/lib/intel64/Release",  // Mac
    System.getenv('INTEL_OPENVINO_DIR') + "/runtime/bin/intel64/Release",  // Windows
    System.getenv('TBB_DIR') + "/../lib/",
    System.getenv('TBB_DIR') + "/../../",
]
```

**Comment by alvoron** [comment]
@ilya-lavrenov can we close it?

**Comment by ilya-lavrenov** [comment]
Tests are red now https://github.com/openvinotoolkit/openvino_contrib/runs/14113209799

**Comment by dkurt** [comment]
https://github.com/openvinotoolkit/openvino_contrib/pull/650 has not been ported to master
