### ISSUE TITLE
Tedious to build and test the demo apps seamlessly

### ISSUE THREAD

**Issue by carun** [openvinotoolkit/openvino_contrib#642]
Thanks for this project. We really want to see if using OpenVINO on Android will speed up inference (we use torch script now) and we haven't been able to do that.

Platform: Linux and Windows (tried on WSL as well)
NDK release version: 25c
OpenVINO: 2022.3
Contrib: master branch

There's enough demo code in this repo for all the modules.

However:

- Either the documentation is incorrect/missing.
- The demo apps don't build in a seamless manner. Building it should build it's dependent as well, but they don't.
- Even if they are build, we are unable to run it properly and it crashes always.

It would be very helpful to get things to work properly. Gradle and cmake are such good build systems that they can invoke each other with the appropriate options and generate the demo APKs.

We tried many different ways to get the arm_plugin module and it's demo to work, but no luck.

My expectation is that beginners should be able to clone the repo, open one of the demo app on Android studio and build and run it seamlessly.

**Comment by alvoron** [comment]
@carun  thank you for raising the issue!
Unfortunately our team capacity is not enough to reproduce issues on Android, so we appreciate if you help us to localize it.
I assume we're talking about this demo and instruction, right? https://github.com/openvinotoolkit/openvino_contrib/blob/master/modules/arm_plugin/demos/coco_detection_android_demo/README.md

Let's start with the first 2 bullets: Either the documentation is incorrect/missing and the demo apps don't build in a seamless manner. Building it should build it's dependent as well, but they don't.

Could you please explain what step result is incorrect \ unexpected?
