### ISSUE TITLE
OpenVINO java version number is outdated

### ISSUE THREAD

**Issue by xuanqing94** [openvinotoolkit/openvino_contrib#873]
https://github.com/openvinotoolkit/openvino_contrib/blob/468701aa12c9960198e8184f6baf66cd695db777/modules/java_api/build.gradle#L14

Hi, may I know how openvino java api version maps to openvino version? For instance here it says openvinoVersion is 2023.2, does that mean it is NOT compatible to most recent openvino C++ lib which is 2024.0?

**Comment by ilya-lavrenov** [comment]
It also contain obsolete inference_engine as a project name:
https://github.com/openvinotoolkit/openvino_contrib/blob/b36781b43e0fbcbbb386619b853d842c67728f3f/modules/java_api/CMakeLists.txt#L3

**Comment by xuanqing94** [comment]
@ilya-lavrenov could you pls answer my question regarding to which release of openvino_contrib matches `openvino==2023.3.0`? The most recent release is 2022.3.0 and I only see a branch called `releases/2023/3`. It looks confusing to me...

**Comment by ilya-lavrenov** [comment]
We have branches, which match OpenVINO releases
![image](https://github.com/openvinotoolkit/openvino_contrib/assets/2566854/438685aa-d639-4ddd-b0b8-f4935cb02311)

**Comment by xuanqing94** [comment]
thank you.
