### ISSUE TITLE
Java tests cannot start on Mac: Could not find OpenVinoTestRunner

### ISSUE THREAD

**Issue by azhogov** [openvinotoolkit/openvino_contrib#95]
Java tests cannot start on Mac
"Error: Could not find or load main class OpenVinoTestRunner"

See logs for details:
https://dev.azure.com/openvinoci/dldt/_build/results?buildId=61614&view=logs&j=a82d9e72-1de4-5bd6-c188-90296135479e&t=e36b0236-8854-50ba-7e69-658d6b092df0

**Comment by dkurt** [comment]
related: https://github.com/openvinotoolkit/openvino_contrib/pull/18
